//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerProf
    {
        public AnswerProf()
        {
            this.TestAnswerProf = new HashSet<TestAnswerProf>();
            this.TestResult = new HashSet<TestResult>();
        }
    
        public int id { get; set; }
        public string Answer { get; set; }
        public int Mark { get; set; }
        public int idTask { get; set; }
    
        public virtual TaskProf TaskProf { get; set; }
        public virtual ICollection<TestAnswerProf> TestAnswerProf { get; set; }
        public virtual ICollection<TestResult> TestResult { get; set; }
    }
}
