//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public College()
        {
            this.CollegeSpecialization = new HashSet<CollegeSpecialization>();
            this.CollegeSubject = new HashSet<CollegeSubject>();
            this.NewsCollege = new HashSet<NewsCollege>();
        }
    
        public int id { get; set; }
        public string NameCollege { get; set; }
        public string Description { get; set; }
        public string LogoCollege { get; set; }
        public Nullable<int> AmountSpecialization { get; set; }
    
        public virtual ICollection<CollegeSpecialization> CollegeSpecialization { get; set; }
        public virtual ICollection<CollegeSubject> CollegeSubject { get; set; }
        public virtual ICollection<NewsCollege> NewsCollege { get; set; }
    }
}
