//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomAppWorkEntities : DbContext
    {
        public DiplomAppWorkEntities()
            : base("name=DiplomAppWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<College> College { get; set; }
        public DbSet<CollegeSpecialization> CollegeSpecialization { get; set; }
        public DbSet<CollegeSubject> CollegeSubject { get; set; }
        public DbSet<EducationalMaterial> EducationalMaterial { get; set; }
        public DbSet<NewsCollege> NewsCollege { get; set; }
        public DbSet<Specialization> Specialization { get; set; }
        public DbSet<SubjectSpecialization> SubjectSpecialization { get; set; }
        public DbSet<SubjectStudies> SubjectStudies { get; set; }
        public DbSet<SubjectTask> SubjectTask { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TaskProf> TaskProf { get; set; }
        public DbSet<UserApp> UserApp { get; set; }
    }
}
