//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalMaterial
    {
        public int id { get; set; }
        public Nullable<int> idSubject { get; set; }
        public string NameBook { get; set; }
        public string Description { get; set; }
        public string LinkBook { get; set; }
        public string AithorBook { get; set; }
        public string PhotoBook { get; set; }
    
        public virtual SubjectStudies SubjectStudies { get; set; }
    }
}
