//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public Specialization()
        {
            this.CollegeSpecialization = new HashSet<CollegeSpecialization>();
            this.SubjectSpecialization = new HashSet<SubjectSpecialization>();
        }
    
        public int id { get; set; }
        public string NameSpecialization { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CollegeSpecialization> CollegeSpecialization { get; set; }
        public virtual ICollection<SubjectSpecialization> SubjectSpecialization { get; set; }
    }
}
