//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTask
    {
        public int id { get; set; }
        public Nullable<int> idSubject { get; set; }
        public Nullable<int> idTask { get; set; }
    
        public virtual SubjectStudies SubjectStudies { get; set; }
        public virtual TaskProf TaskProf { get; set; }
    }
}
