//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskProf
    {
        public TaskProf()
        {
            this.AnswerProf = new HashSet<AnswerProf>();
        }
    
        public int id { get; set; }
        public string Exercise { get; set; }
    
        public virtual ICollection<AnswerProf> AnswerProf { get; set; }
    }
}
