//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public TestResult()
        {
            this.TestAnswerProf = new HashSet<TestAnswerProf>();
        }
    
        public int id { get; set; }
        public int UserMarkForQuestion { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idAnswer { get; set; }
    
        public virtual AnswerProf AnswerProf { get; set; }
        public virtual ICollection<TestAnswerProf> TestAnswerProf { get; set; }
        public virtual UserApp UserApp { get; set; }
    }
}
